### ISSUE TITLE
Data conversion in main.py

### ISSUE THREAD

**Issue by janweinreich** [daenuprobst/molzip#18]
in the benchmark script the 
https://github.com/daenuprobst/molzip/blob/e8037b12c03ef91d1db9d099ef1c545ef2dee119/main.py#L138
function converts all labels to int eventhough regression tasks need float. 
(for instance the free energy is -2.254 not -2 !
So if I am not mistaken we have to redo all regression benchmarks!

**Comment by janweinreich** [comment]
I have rerun the calculations with updated settings, so floats for regression, and getting these numbers:
# Results Gzip-based Molecular Classification

|     Data Set      | Split  |AUROC/RMSE (Valid)|F1/MAE (Valid) |AUROC/RMSE (Test)| F1/MAE (Test) |
|-------------------|--------|------------------|---------------|-----------------|---------------|
|freesolv           |random  |0.682 +/- 0.053   |0.547 +/- 0.053|0.864 +/- 0.053  |0.646 +/- 0.053|
|freesolv (KRR)     |random  |0.985 +/- 0.025   |0.718 +/- 0.025|0.9 +/- 0.025    |0.655 +/- 0.025|
|delaney            |random  |1.482 +/- 0.023   |1.14 +/- 0.023 |1.493 +/- 0.023  |1.117 +/- 0.023|
|lipo               |random  |1.016 +/- 0.062   |0.804 +/- 0.062|0.992 +/- 0.062  |0.789 +/- 0.062|
|sider              |scaffold|0.551 +/- 0.0     |0.707 +/- 0.0  |0.577 +/- 0.0    |0.666 +/- 0.0  |
|sider              |random  |0.589 +/- 0.002   |0.662 +/- 0.002|0.599 +/- 0.002  |0.656 +/- 0.002|
|bbbp               |scaffold|0.931 +/- 0.0     |0.931 +/- 0.0  |0.639 +/- 0.0    |0.627 +/- 0.0  |
|bace_classification|scaffold|0.694 +/- 0.0     |0.702 +/- 0.0  |0.701 +/- 0.0    |0.697 +/- 0.0  |
|bace_classification|random  |0.81 +/- 0.023    |0.805 +/- 0.023|0.813 +/- 0.023  |0.812 +/- 0.023|
|clintox            |scaffold|0.805 +/- 0.0     |0.854 +/- 0.0  |0.891 +/- 0.0    |0.891 +/- 0.0  |
|clintox            |random  |0.885 +/- 0.036   |0.897 +/- 0.036|0.866 +/- 0.036  |0.906 +/- 0.036|
|tox21              |scaffold|0.635 +/- 0.0     |0.247 +/- 0.0  |0.618 +/- 0.0    |0.227 +/- 0.0  |
|tox21              |random  |0.715 +/- 0.005   |0.307 +/- 0.005|0.687 +/- 0.005  |0.282 +/- 0.005|
|hiv                |scaffold|0.714 +/- 0.0     |0.901 +/- 0.0  |0.689 +/- 0.0    |0.887 +/- 0.0  |
|muv                |random  |0.277 +/- 0.277   |0.035 +/- 0.277|0.136 +/- 0.277  |0.048 +/- 0.277|
|schneider          |random  |0.0 +/- 0.0       |0.801 +/- 0.0  |0.0 +/- 0.0      |0.801 +/- 0.0  |

as far as i can tell all other numbers are still the same as it should be. @daenuprobst (just tagging you for cross check that I didnt mess up). if you agree I will push the new main.py

**Comment by daenuprobst** [comment]
Hey, looks good to me, awesome work! And I'm still amazed that this actually works 😁

**Comment by janweinreich** [comment]
yes and surprisingly KNN with gzip is even comparable to physics based representations on FreeSolv (reached 0.6 kcal/mol with FCHL19 and additional MD simulations and KRR) - although at smaller trainingsset size than here. Also surprising that KRR does not at all help here ...
